### ISSUE TITLE
updated lang files for EN-GB and EN-US

### ISSUE THREAD

**Issue by lolouk44** [Martin-Gleiss/smartvisu#105]
not sure how to help with improvements so raised an issue.
I renamed lang_en.txt into lang_en-us.txt
I cloned lang_en-us.txt into lang_en-gb.txt

Changes:
en-gb has british settings (e.g. d-m-y, Celcius)
I also capitalised the wind directions for both files (e.g. North-North-West instead of North-north-west.)
Also corrected "South-sud-east" into "South-South-East" for both yr.no and wunderground

[lang_en-us.txt](https://github.com/Martin-Gleiss/smartvisu/files/516434/lang_en-us.txt)
[lang_en-gb.txt](https://github.com/Martin-Gleiss/smartvisu/files/516435/lang_en-gb.txt)

**Comment by smaiLee** [comment]
I'm sorry for not commenting such a long time.

The problem is the configuration, particularly the backward compatibility if someone has set lang="en" in own config.php.

At the moment the configuration is saved as php constants which are absolutely immutable.
I'm working on refactoring of configuration, so it should be possible to automatically change "en" to "en-us" on loading.

Afterwards we can also define different specifications for 'de-de', 'de-ch' and, if required, for 'de-at' (are there any differences between 'de-at' and 'de-de'?)
I assume also in french language do exist different formats for several countries. Does anybody know more?

**Comment by lolouk44** [comment]
Thanks Stefan.
For French, there can be a few options, though I'm not sure there would be much differences between the variations (I'm a French national):
fr		French (Standard)
fr-be	French (Belgium)
fr-ca		French (Canada)
fr-ch	French (Switzerland)
fr-lu		French (Luxembourg)

**Comment by smaiLee** [comment]
I'm thinking about a 2-layer solution:
Ex: en.txt as base for english, then en-gb.txt containing just the differences to override. Thus we reduce redundances.

As format I would change to ini instead of the current txt which is then evaluated by php eval() function.
I'm also converting config.php to ini.
