### ISSUE TITLE
Problems with plots showing boolean values

### ISSUE THREAD

**Issue by onkelandy** [Martin-Gleiss/smartvisu#122]
a) When smartvisu displays a boolean plot where the value before a change is outside the defined time frame (i.e. 3h) the stair line starts right in the middle of the plot and not at the beginning.

b) Showing boolean values correctly doesn't work even with data coming from MySQL (DBLog plugin for smarthome.py) and the "on" function. I would expect the plot to show exactly when an item was turned on and off. By adjusting the number of data points to a much higher level the problem can somehow be reduced but not really solved.
![plot_werteproblem](https://cloud.githubusercontent.com/assets/7084934/20424646/3acfbb1e-ad77-11e6-8c9e-7009756b987f.JPG)

**Comment by smaiLee** [comment]
Unfortunately I don't see any practicable solution for your issues in smartVISU.
I think if there is any it has to be in SmartHomeNG.

a) What should be shown before the first known datapoint in your opinion?
A possible solution could be to start the plot at this point in time instead of the configured one. But if you have multiple series this doesn't help either.
Another approach would be that SmartHomeNG sends always one value before the first one requested.
I think this issue isn't unique to boolean values but affects any plotted data.

b) The cause of this has to be in SmartHomeNG, as far as I know the plots just shows the data as they are sent by backend.

But I have made other improvements for plotting boolean values, have a look at the new parameter *ytype = 'boolean'* and ymin/ymax in development version.

**Comment by onkelandy** [comment]
You are right, the problems are based on the database implementation of SmarthomeNG as covered in issue 2 and 3 here: https://github.com/smarthomeNG/smarthome/issues/165

Problem b can be solved somehow by increasing the number of values by 10 or even 100.

I'll try the new stuff as soon as I find time to update smartvisu to the latest version. What exactly does ytype=boolean do?

**Comment by smaiLee** [comment]
You can define label for low and high state. This is implemented as categories in highcharts.

Following screenshot shows the right axis as boolean:
![screenshot](https://cloud.githubusercontent.com/assets/20517059/23787576/00cf6a50-0573-11e7-9073-d70e7324cc79.png)

**Comment by onkelandy** [comment]
I've just tried the "boolean" thing and the look of the period plot changed indeed. But how can I change the labels to "On" and "Off"? It's still 0 and 1 here..

**Comment by smaiLee** [comment]
Pass the strings for ymin and ymax (yes, I know, this is not a very proper way)

> **ymin**
> the minimum for each y-axis; multiples in array form: [ min_y-axis1, min_y-axis2, ...] (optional)
> if the axis type is boolean the passed value will be the label of the low state (e.g. 'Off')
>
> **ymax**
> the maximum for each y-axis; multiples in array form: [ max_y-axis1, max_y-axis2, ...] (optional)
> if the axis type is boolean the passed value will be the label of the high state (e.g. 'On')

**Comment by onkelandy** [comment]
Oh, that didn't work before.. maybe I did something else wrong. Now it's working fine. Thanks!
