### ISSUE TITLE
plot.multiaxis: max value on each axis not working correctly

### ISSUE THREAD

**Issue by onkelandy** [Martin-Gleiss/smartvisu#124]
If I set "260" as the max value for a normal plot.period I get 300 as the max y value. That's fine so far. But as soon as I change the plot to a multiaxis the max y value changes to 400.
The second y axis is set to 1 or 2 as a max and shows 4. 
```
{{ plot.multiaxis('terrasse.og.plot', ['licht.og.terrasse.screens.warm.dimmen', 'licht.og.terrasse.screens.kalt.dimmen', 'licht.og.terrasse.decke.dimmen', 'licht.og.terrasse.wand.SA'], 'avg', '12h', '', '', ['260','2'], '1000', ['Screens warm','Screens kalt','Decke','Wand'], ['#d00', '#00d', '#540', '#ddd'], ['stair', 'stair', 'stair', 'stair'], ['Uhrzeit', 'Dimmen', 'An/Aus'], '30s', [1,1,1,2],[0,1],['#f00','#0a0']) }}
```

**Comment by smaiLee** [comment]
This behaviour is because of an option called *alignTicks* which is set by default. Ticks on left and right axis are alignee then.
On normal plots this makes sense because they look weird if position of left and right ticks differ.

Either we could expose this option so it can be unset by parameter. Or we disable this option if one axis has a maximum between 1 and 2.
Or even better: both of them, we expose it and disable it by default on axis max. between 1 and 2.

**Comment by smaiLee** [comment]
I solved this by adding possibility to define boolean axes.
This is done by passing strings for yMin and yMax, see 6th example in docu of plots.period (currently in develop branch). This strings are used as labels for false and true.
Technically they are passed as [categories](http://api.highcharts.com/highcharts/yAxis.categories) to Highcharts.
