### ISSUE TITLE
Problem when naming an html file the same as a widget "group"

### ISSUE THREAD

**Issue by onkelandy** [Martin-Gleiss/smartvisu#217]
If you have an html file in a standard page (e.g. multimedia.html in your own pages folder) you get a huge problem when accessing a widget with the same group name, e.g. multimedia(.audio, etc.). The page does not get loaded at all as the "import" statements import the wrong file (the one from the pages folder instead of the widgets folder)?

**Comment by smaiLee** [comment]
That's an architectural problem which most likely exists since beginning. There's no simple solution therefore.

The only solution I see is to add a namespace to widget library. But then every import has to be prefixed (e.g. `{% import "@widgets/multimedia.html" as multimedia %}` instead of `{% import "multimedia.html" as multimedia %}`)

This would be a real breaking change as most users have such imports in own pages.
(In develop these custom imports are not necessary anymore, but up to v2.8 not all widgets got imported in pages/base/root.html.)

To give more time for migration I could add the namespace additionally to the existing un-prefixed path, so they can be used already.
But as long as the existing path is not removed the problem will remain.

**Comment by onkelandy** [comment]
So maybe just fixing it for 2.9 by using optional namespaces and mentioning this in the docu / fundamentals (?) would be an option?
I guess the problem doesn't occur too often but when it does it sucks ;)

**Comment by smaiLee** [comment]
The word "option" led to an idea. :thumbsup:
A new option in configuration could be introduced to set compatibility level. This could also be used for other (future) breaking changes.

**Comment by onkelandy** [comment]
As custom imports are not necessary anymore the namespace feature could be integrated now/for the next release?

**Comment by wvhn** [comment]
introduced with #769 
import of widgets now uses the namespace `@widgets`, e.g. `{% import "@widgets/mywidget.html" as mywidget %}`. Importing widgets without namespace is deprecated and will be removed in a later version.

**Comment by wvhn** [comment]
introduced with #769 
Import of widgets now uses the namespace `@widgets`, e.g. `{% import "@widgets/mywidget.html" as mywidet %}`. All smartVISU paths allowed for widgets are members of this namespace. Import without namespace is deprecated and will be removed in a later version.
