### ISSUE TITLE
basic.select with dynamic options

### ISSUE THREAD

**Issue by smaiLee** [Martin-Gleiss/smartvisu#221]
basic.select (or a similar widget) should support dynamic options (i.e. value, icon and text) passed in an item.

Use cases see:
- https://knx-user-forum.de/forum/supportforen/smartvisu/1306190-widget-mit-dem-in-smartvisu-ein-dict-item-geschrieben-werden-kann?p=1307180#post1307180
- https://knx-user-forum.de/forum/supportforen/smartvisu/1298321-knx-szenen-widget?p=1307036#post1307036

**Comment by wvhn** [comment]
realized for "menu" type. I decided to not implement other types since changing the no. of buttons w/ changing icons would look weird on a "steady" page.

How could the function be realized?
Idea (not tested):
- call eg. some 8 dummy basic.stateswitches, put them in individual spans with individual ids and hide them with style="display: none"
- define a 3rd list item for the icon names
- fill the icon names, option values and texts with js code into the stateswitches and display the amount of switches defined by the list items.
