### ISSUE TITLE
dropin widget are not found

### ISSUE THREAD

**Issue by onkelandy** [Martin-Gleiss/smartvisu#232]
It seems like smartvisu is looking in the dropin folder, but not dropin/widgets?

**Comment by onkelandy** [comment]
I put the file widget_stateengine.html in the folder dropin/widgets and try to include in a test.html file like this:
```
{% import "widget_stateengine.html" as stateengine %}
```

I get the following error on loading the page, but no error if the widget_stateengine.html is in dropin folder:
```
error: Unable to find template "widget_stateengine.html" (looked into: /var/www/html/smartVISU2.9/apps, /var/www/html/smartVISU2.9/pages/flexible-quad-Andy, /var/www/html/smartVISU2.9/dropins, /var/www/html/smartVISU2.9/pages/base, /var/www/html/smartVISU2.9/widgets).

```

**Comment by smaiLee** [comment]
As described in https://github.com/Martin-Gleiss/smartvisu/blob/develop/dropins/README.md#widgets dropin widgets are imported automatucally, there's no need to import them yourself.

**Comment by onkelandy** [comment]
O perfect. Sorry, wasn't that obvious for me. Maybe a "Any valid .html file in widgets folder gets automatically imported as widget library." would be totally clear.

**Comment by onkelandy** [comment]
OK, so the import works fine for pages but NOT for widgets.
Example: I create own widgets in quad.html and there I have to import for a specific widget other widgets. And this only works from the dropins folder but not from dropins/widgets. @smaiLee

**Comment by smaiLee** [comment]
You can import them by adding the folder `widgets:`
```Twig
{% import "widgets/widget_stateengine.html" as stateengine %}
```

The reason why dropins/widgets is not in Twig path is to avoid naming conflicts. Otherwise a widget library which has the same name as a page can't get loaded.

I already implemented (but not yet committed) [namespaces](https://twig.symfony.com/doc/2.x/api.html#built-in-loaders) to reduce naming conflicts any more. Then you can import widgets as `@widgets/my.html` and pages as `@pages/my.html`. (Additionally the old paths without namespace will still be valid for backward compatibility.)
