### ISSUE TITLE
Check Twig expressions in Template Checker

### ISSUE THREAD

**Issue by smaiLee** [Martin-Gleiss/smartvisu#238]
Template Checker should check if the parameters or at least the widgets are valid Twig expressions.
This could be achieved by instantiating Twig similar to [Lint in Symfony](https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Twig/Command/LintCommand.php). But as there are just single expressions to check, using [ExpressionParser](https://github.com/twigphp/Twig/blob/1.x/src/ExpressionParser.php) of Twig could be enough.
(Entire template could additionally still be checked like in Lint.)

**Comment by onkelandy** [comment]
Additionally the template checker should take < and > within twig tags into consideration when checking for HTML problems.

**Comment by onkelandy** [comment]
Furthermore in the replacement suggestion the ' ' should be implemented. Be aware that the behaviour has to be different when dealing with arrays than with strings.
https://knx-user-forum.de/forum/supportforen/smartvisu/1427933-umstieg-auf-smartvisu2-9-basic-symbol-probleme

**Comment by wvhn** [comment]
Thanks to GPT4 I was able to integrate both - a twig syntax check for the entire template and a syntax check for twig tags / macro calls (based on https://stackoverflow.com/questions/27191916/check-if-string-has-valid-twig-syntax). During testing it turned out that the latter gives no additional useful information compared to the current widget parameter checks. So I removed it again. 
With #971 there is now a template syntax check for twig.
