### ISSUE TITLE
Merge request: New contact lookup service

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Martin-Gleiss/smartvisu#40]
```
With this change the phone service is able to look up contacts.
This is especially helpful for phone services which do not support contact 
details (e.g. the Telekom Speedport).

```

https://github.com/willjoha/smartvisu/commit/95569a3b3debbf54e5a67c76e4d2d6077ecf98e3

Original issue reported on code.google.com by `willj...@gmail.com` on 8 Apr 2015 at 8:26

**Comment by wvhn** [comment]
I am closing this after 6 years since I think all modern routers will provide contact information and the effort of setting up an extra contact.csv in smartVISU is too high. I was checking whether it might be possible to provide the service on smartvisu-newstuff, but there are too many alterations to be made in existing services and in the meanwhile changed config page.

Thanks nevertheless for the contribution.
