### ISSUE TITLE
V3.x Performance 

### ISSUE THREAD

**Issue by jksd** [Martin-Gleiss/smartvisu#697]
Hi,
I've running smartvisu v2.9 and v3.x running with the same project and the same extend of functions (all deprecated stuff replaced). You really feel v3.x being less performant as v2.9.  Especially on slower panel hardware, it's no fun with 3.x.

I found this topic before in the web, too. Is there a reason for it ?

Best regards ,
Jörk

PS: I reduced svg size of standard icons about 50% (https://jakearchibald.github.io/svgomg/). Loading time ist better with smartvisu v2.9 and v3.2. Visu quality is still good.

**Comment by wvhn** [comment]
Hi Jörk,
Performance was one reason why I changed the menu structure in v3.2. Before, all ressources - even for config page and widget assistant - had been loaded for every page. Now, the system uses jQm multipage navigation more consequently and ressource-intensive pages (config, widgetassistant, templatechecker) are treated separately. Timing measurements showed noticeable improvements versus v3.1. Enabling smartVISU Cache is still the most important measure to boost performance. Then, performance with a 1st gereration Rapberry and an old iPad 2 is still OK from my perspective.

I would be interested to learn about your experiences with v3.2 in comparison to v3.1. 

Best regards
Wolfram

P.S.: in the forums there are almost no hints on lacking performance of smartVISU. I have seen only one user complaining. He seems to have a special Docker setup which could slow down communication.

**Comment by jksd** [comment]
Hi Wolfram (this time in English again - perhaps German could be faster),

my main window of the visual is quite complex. Behind the cells, small dialogs are included. I like a direct selection of functionality without moving through menu cascades.

Environment:
Backend: Raspberry 4B booting and running from SSD (hosting smartvisu and fhem)
Panel: XORO Megapad 2404 v2 (24 Zoll LCD FHD kapazitives Multitouch IPS Display, Android 5.1, Quad Core Prozessor mit 1.8GHz, GPU:Mali T764, 2GB RAM, 16GB interner Speicher, Dualband-WLAN, Bluetooth, Gigabit-LAN)
Communication via fronthem

Please see my video uploaded to GoogleDrive:
https://drive.google.com/file/d/1BaeBa4pEJCLHycbUSTNPdaG_jaxBPQwY/view?usp=sharing

Reload smartvisu V2.9 incl. Smartvisu cache=enabled + Browser-Cache=enabled:
00:03 - 00:12 :	 9s : Page load, Result: All data available, values, window states, etc show current status
00:12 - 00:25 :	13s : css
               ======
		22s

Initial start smartvisu V3.2 incl. smartvisu cache=enabled - Browser cache enabled
00:51 - 01:09 : 18s : Page load. Result: All data available
01:09 - 01:27 : 18s : css
               =====
                36s

1st Reload smartvisu V3.2 incl. Smartvisu cache=enabled + Browser-Cache=enabled:
01:37 - 01:50 : 13s : Page load. Result: All data available (-5s due to Browser cache)
01:50 - 02:09 : 19s : css
               =====
                32s (+10s compared to V2.9)

2nd Reload smartvisu V3.2 incl. Smartvisu cache=enabled + Browser-Cache=enabled:
02:18 - 02:32 : 14s : Page load. Result: All data available
02:32 - 02:55 : 23s : css
               =====
                37s (+15s compared to V2.9)

Conclusion: SV V3.2 takes 50% more time. Most of it when rendering css.

When running smartvisu on iPhone 11 or 12, it’s much faster - but v3.2 still takes some extra second(s).

Both setups (v2.9 and v3.2) took about additional 3s more before reducing SVG size at XORO panel (test results above after SVG shrink). Resizing the SVGs should be done independent of this case. You really feel the difference.

You’re welcome with any suggestions :-).

Thank you in advance,
Jörk

PS: I haven't done additional tests with v3.1. As far as I can remember, there was no significant difference compared to v3.2 in my use-case.

**Comment by wvhn** [comment]
Hi Jörk,
can you come to the forum and send me an PN with a link to your entire SV folder? I would like to test your pages in order to  understand more of the root causes for this behaviour. The browser developer tools can give more hints on the time-consuming routines.
What you can do yourself:
-  edit your menu and remove "data-ajax = false" from the links which causes the page to load from scratch (to be seen after activating your home button) instead of taking it from jQuery mobile page memory via ajax. This should boost performance quite a lot.
- if you don't use the roundslider or status.toast widgets, you can remove their jQuery plugins from the import in root.html. Line 50 / 51 is .css import and line 130 / 131 is .js import. These two plugins were the only new external packages brought into smartVISU. It would be interesting to see if there is some impact.
- copy ./vendor/plot.highcharts from v2.9 to v3.2 (after renaming the folder in v3.2). This package has grown a lot over the versions. Maybe you won't be able to use all features of the plot widgets but the functions shown in the docu are working. Also here it would be interesting to see if there is an impact on performance.

Thanks for the support and best regards
Wolfram
