### ISSUE TITLE
clean up <img ...> to use svg icons and provide an alt attribute

### ISSUE THREAD

**Issue by smaiLee** [Martin-Gleiss/smartvisu#70]
_From @bmxp on August 26, 2016 8:58_

Within the Rep are several img defined in widgets. I would prefer to have only SVG as icons and it would be good to provide the alt attribute to prevent the warnings from html checkers. Please give opinions regarding at least the alt attribute.

_Copied from original issue: SmartVisuTNG/smartvisu#33_

**Comment by msinn** [comment]
I think the alt attributes are a bit of an overhead for tge visu (have to be transfered and rendered). Do we really need them, just to make an html checker happy?

**Comment by smaiLee** [comment]
alt tags are essential for visually impaired people. Proper solution would be, that any widget with an image has a parameter for alt tag. But this would be quite some work to do.

As an alternative we could just set the icon name as alt tag. This satisfies html checkers but is not very usefull for humans.
But actually i dont know if visually impaired people realy use a 'visualization' like smartVISU, so this could be sufficient.

**Comment by Martin-Gleiss** [comment]
I think a alt tag would be fine for some people. A new parameter would be oversized, if we like to indroduce it we should use ne name.

**Comment by msinn** [comment]
I think I found all pngs in widgets that rely on the /icons folder and replaced them by svgs.

The remaining pngs reference pictures an /pages/base/pics and can remain pngs (since we have no svgs for these pictures anyhow).

**Comment by smaiLee** [comment]
Please check if any more alt attributes are desirable, otherwise I will close this.

**Comment by bmxp** [comment]
This [question](http://stackoverflow.com/questions/4697100/accessibility-recommended-alt-text-convention-for-svg-and-mathml) handles the same issue more in general.
Besides from making a html checker happier I think it might be useful to have <alt> for PNG if they are displayed as such when the real image data is absent.
But a "Visu" for visually impaired people is difficult to imagine so I think when we have alt with the image name for png and the like and maybe for svg the title attribute and the attrib role=img. But since the most PNG (if not all) seems to have been replaced by SVG this thread might be closed then.
