### ISSUE TITLE
Reactivate ioBroker project and integrate smartvisu 3.2?

### ISSUE THREAD

**Issue by Apollon77** [Martin-Gleiss/smartvisu#784]
Hi,

We were in contact back in 2020 to integrate smartvisu with ioBroker ... Now while cheking for updates I saw that you have finished the 3.x. Cool amd congratulations.

What do you think ... should we try to reactivate and update the project?

Thank you for info, and happy to hear your opinion ... if not here then at iobroker@fischer-ka.de

**Comment by wvhn** [comment]
Hi Ingo,
Sure can we do this. First of all I would ask you to install smartVISU v3.2.2 in a new directory on your server and test the functionality with ioBroker. You can leave your production version of smartVISU unchanged and have it run in parallel. Just copy your Visu pages to the new directory structure. 

Of course, if ioBroker features new functions or commands on the interface we have to integrate these into the driver. But the actual driver covers the same functions we had back then in 2020.

Best regards
Wolfram

**Comment by Apollon77** [comment]
Hey, in fact I do not use smartvisu at all, I'm "just" the devloper of an adapter :-)) I will try to get it running again ... do you by chance remember/have the link to instructions how to setup? In fact the socketio adapter still exists (when I remember correctly this is used) - so all should be the same. ioBroker in the meantime also have a "pure websockets" wadapter with the same commandfs that just do not use socket.io but pure ws.

**Comment by wvhn** [comment]
Setup is quite easy: https://github.com/Martin-Gleiss/smartvisu/wiki/Installation-SV-in-Verbindung-mit-iobroker
You could then copy one of the examples to ./pages/&lt;youPages> folder and just replace the item names in the widget parameters with your own items. Or you just use the Widget Assistant.

**Comment by wvhn** [comment]
@Apollon77 @uwe5
I have changed smarthomeNG and offline driver so that they can order (or cancel) series for individual plots. There are two "public" functions `startseries(plotwidget)` and `stopseries(plotwidget)`. If the parameter "plotwidget" is empty all series of a page get ordered or cancelled. If "plotwidget" is specified, only the series of that plot get ordered / cancelled. A series must not be  cancelled (unsubscribed) for an individual plot if the same series is also used in other plots on the page.

Code example from smarthomeNG driver:
```
	/**
	 * (re-)start all subscribed series of a single plot widget
	 * or - if parameter ist empty - all plot widgets on the active page
	 */
	startseries: function (plotwidget) {
		io.plotcontrol('series', plotwidget);
	},
	
	/**
	 * stop all subscribed series of a single plot widget
	 * or - if parameter ist empty - all plot widgets on the active page
	 */
	stopseries: function (plotwidget) {
		io.plotcontrol('series_cancel', plotwidget);
	},

	/**
         * identify all subscribed series and execute given command
         * /
	plotcontrol: function(seriescmd, plotwidget) {
		var unique = Array();
		var plotWidgets = [];
		var singleCancel = (seriescmd == 'series_cancel') && (plotwidget != undefined);
		if (plotwidget === undefined)
			plotWidgets = widget.plot();
		else
			plotWidgets = plotwidget;
	
		plotWidgets.each(function (idx) {
			var items = widget.explode($(this).attr('data-item'));
			for (var i = 0; i < items.length; i++) {
				var definition = widget.parseseries(items[i]);
		
				// prevent cancelling a series if not only the specified plot widget has subscribed it 
				// TO DO: check what happens if the specified plot requests a series already available for a different plot 
				if ((singleCancel == true) && (widget.plot(items[i]).length > 1))
					unique[items[i]] = 1;
					
				if (!unique[items[i]] && definition != null) {
					io.send({'cmd': seriescmd, 'item': definition.item, 'series': definition.mode, 'start': definition.start, 'end': definition.end, 'count': definition.count});
					unique[items[i]] = 1;
					if (singleCancel == true)
						delete widget.buffer[items[i]];
				}
			}
		});
	}, 
```
The code is not yet in the GitHub repository. 

The extension is needed for a new widget which can analyse plots by shifting them in time-range, i.e. it cancels the actual series in the plot and orders new series for the same items with a changed time range. 
https://github.com/smartVISU-newstuff/widgets/tree/master/plot_timeshift

An according adaption of the iobroker driver - and maybe a test with the widget - would be highly appreciated ;)

regards
Wolfram
