### ISSUE TITLE
Dynamic icons can't be colored

### ISSUE THREAD

**Issue by msinn** [Martin-Gleiss/smartvisu#80]
Right now, it is not possible to specify a color for dynamic icons.

I am gonna add the option for colorization to the dynamic icons.

**Comment by Martin-Gleiss** [comment]
In my opinion it should be done with a css class.

**Comment by smaiLee** [comment]
Perhaps we should rethink icon coloring at all.
At the moment there are some widgets with seperate color parameter, others need CSS. And some handle SVG and PNG seperate, others do just print out the given file as <img>.
And only SVG with class icon1 are made inline and thereby stylable by CSS. But what if a theme wants to have a default color other than white?

**Comment by msinn** [comment]
I was thinking of implementing it, like it is i plemented for the majority of the widgets:

A separate parameter which can be icon0, icon1 (defined in css) or a color code.

For the future I like the idea of defining more colors than icon0 and icon1 in the design, but individual coloring should be an option in the future. We dont know what the users want to do with coloring. So I am no fan of removing the color parameter.

**Comment by smaiLee** [comment]
I was unclear: Custom colors should be allowed.

I was thinking of just not pass it as a separate parameter but as part of the icon param.
This could look like:

    {{ basic.dual('dual2', '...', 'control_arrow_up', 'control_arrow_down .icon1') }}
    {{ basic.dual('dual2', '...', 'control_arrow_up #445566', 'control_arrow_down red') }}

But you are right. As most widgets already have the color param, we should not change this.

I had particularly basic.multistate in mind, where you have a list of icons. I just don't like solutions, where you have to pass multiple lists of same length, because they are prone to wrong definitions. But it's to late to change this.

So, just forget about my comment to color params but think about my other suggestions :grinning:

**Comment by msinn** [comment]
Implemented

**Comment by Martin-Gleiss** [comment]
I think, that is not a very good solution. Now some widgets have an color option, some not. We should remove the color options from the parameters, and deliver some examples in css with colored widgets. If you put some switches together to an device, you will need many color options...

**Comment by msinn** [comment]
I don't understand what you mean. All dynamic icons have a color option.

**Comment by msinn** [comment]
I don't think it is user friendly to force people to mess with css only if they want an icon in another color. Btw.: Martin, you started adding the color parameter to other widgets long ago (before you deserted smartVISU).

**Comment by smaiLee** [comment]
already done
