### ISSUE TITLE
speeds up page loading when there is a lot of data in the plots (iobroker)

### ISSUE THREAD

**Issue by uwe5** [Martin-Gleiss/smartvisu#807]
Hi Wolfram,

With a mobile phone or tablet, the page with plots was still very slow to load, I fixed that.
Start subscribing and draw with a delay in the plotsdata so the "normal" widgets are populated with data first. This speeds up page loading when there is a lot of data in the plots, when the page is loaded for the first time.

greetings Uwe

here's the fix:
[io_iobroker.tar.gz](https://github.com/Martin-Gleiss/smartvisu/files/10244488/io_iobroker.tar.gz)

**Comment by wvhn** [comment]
Hi Uwe,
thanks again. There was a little mess in the layout because the editor replaced some blanks by tabs, I guess. I have corrected this and pushed the result to the develop branch.

Is there a mechanism to unsubscribe items and plots from the backend, as well? Or does iobroker send updates even to visu pages where these items are not required? 

In smarthomeNG,  we have the method "io.stopseries()"  which sends a cancel command for each subscribed plot. This method is empty in the iobroker driver and could be used ;) . smartVISU calls this method on every page change.  

The method could also be used to stop subscription of "normal" items in iobroker. (We don't need that in smarthomeNG since we order always the complete set of items on a visu page with the "monitor" command and this subscription is replaced with the new set of items if you change page. )

Greetings
Wolfram

**Comment by uwe5** [comment]
Hi Wolfram,
Yes, there is something. Here is an example
[https://github.com/ioBroker/ioBroker.socketio/blob/master/example/conn.js](url)
in line 520.

So you would have to do an 'unsubscribe' somehow.
About as?

	stopseries: function () {
		if (io.isConnected) {
			var items = widget.listeners();
			io.plots.forEach(plot => {
				items.push(plot[0]);
			});
			io.socket.emit('unsubscribe', items);
			io.read(items);
		}
	}

I just installed it and it seems to be working. I checked it with the browser debugger.

Greetings
Uwe

**Comment by wvhn** [comment]
Thanks! 
I added the function and merged the commit with PR #809
