### ISSUE TITLE
only part of calendar is shown

### ISSUE THREAD

**Issue by georgtroska** [Martin-Gleiss/smartvisu#828]
Hi Martin,
thanks for this great tool.

I ran into an issue I do not know its origin, maybe it's just a misconfiguration. 
I added a calendar of my local waste-company
[https://gwa-abfuhrkalender.de/ical.html?jahr=2023&kommune=7&bezirk=238&filter=3,6,2,1,13,25,7](url)

I was able to get the calendar-list running. The ics file is downloaded and the calendar shows up. Unfortunately, it shows me only entries with the title "Restmüll 2-wchtl." From the ics file I can see that there are several other events in the calendar. I can also import the calendar into outlook and can see the other events.

Is there maybe something in the code filtering on the the string "müll". there other entries are called "Biotonne", "Wertstofftonne", ...

Would be nice to to hear something - thanks in advance
Georg

**Comment by wvhn** [comment]
Hi Georg,

the problem is in the calendar URL. smartVISU accepts a list of multiple calendars separated by commas. Here, the waste company puts garbage into the URL ;) by using commas as  separators for their filters. So smartVISU interprets the filters as additional URLs instead of passing these as parameters to the real URL. 

You can work around this by escaping the commas in the filter list, i.e. replace each comma by `%2C` In the calendar config entry of smartVISU. 

Please come to the support forum if you have any more questions: https://knx-user-forum.de/forum/supportforen/smartvisu

Regards
Wolfram

**Comment by georgtroska** [comment]
Works!

I deleted the filter settings in the url

 

Thanks a lot

 

Georg

 

Von: wvhn ***@***.***> 
Gesendet: Freitag, 6. Januar 2023 00:54
An: Martin-Gleiss/smartvisu ***@***.***>
Cc: georgtroska ***@***.***>; Author ***@***.***>
Betreff: Re: [Martin-Gleiss/smartvisu] only part of calendar is shown (Issue #828)

 

Closed #828 <https://github.com/Martin-Gleiss/smartvisu/issues/828>  as completed.
