### ISSUE TITLE
Widget "basic.select" - Bildschirmhöhe Bug 

### ISSUE THREAD

**Issue by mm2706** [Martin-Gleiss/smartvisu#918]
Wenn die Bildschirmhöhe kleiner ist, wie die der Inhalt Liste wird diese in einem Pop-Up geöffnet. In dem Pop-Up lassen sich die Inhalte auswählen, aber das Value wird nicht übernommen. Lediglich das Pop-Up schließt sich wieder. Die Konsole gibt keine Fehlermeldung aus. 

Das Problem lässt sich auch in der [Dokumentation](https://docu.smartvisu.de/3.3/index.php?page=basic/widget_basic.select) nachstellen. Einfach mal das Browserfenster auf kleinste Höhe verstellen und beim `{{ basic.select('', 'bath.multistate', '', [5,6,7], '', ['Down', 'Left', 'Up']) }}` ausprobieren. 

Visu-Version: 3.3.1
Verwendete Browser zum Test: Safari 16.5 und Google Chrome 116

**Comment by wvhn** [comment]
Thanks for the hint. 
jQuery mobile displays the select menu on an extra page to make it scrollable if the select list is higher than the screen size. This caused the update method (triggered by pagecontainerchange) to appear before the 'change' event.
Now we check whether item value equals the selected option on the select menu before updating and otherwise wait for the change event.

closed with #919
